const GROQ_BASE='https://api.groq.com/openai/v1/chat/completions', GROQ_MODEL='llama3-70b-8192'
const groqKey=()=>globalThis.__GROQ_KEY||import.meta.env.VITE_GROQ_API_KEY||''
async function groqChat(system,user,maxTokens=200){const key=groqKey();if(!key)return '';try{const res=await fetch(GROQ_BASE,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:GROQ_MODEL,max_tokens:maxTokens,temperature:0.85,messages:[{role:'system',content:system},{role:'user',content:user}]})});const d=await res.json();return d.choices?.[0]?.message?.content?.trim()||''}catch{return ''}}
const NPC_FB=['The road ahead is treacherous.','Strange sounds from the ruins at night.','You carry the look of a warrior.','These are dark times. Bandits grow bolder.','Safe travels, samurai.','I once saw a demon in the mountain pass.','The shrine has been silent for weeks.','They say the old ruins hold treasure.','A ronin passed through yesterday.','Honor your ancestors, warrior.']
export async function generateNPCDialogue(npcType,playerName,location,context){const key=groqKey();if(!key)return NPC_FB[Math.floor(Math.random()*NPC_FB.length)];const text=await groqChat(`You are ${npcType} in feudal Japan. Speak in character. 2-3 sentences max.`,`The warrior ${playerName} approaches in ${location}. Context: ${context}. What do you say?`,120);return text||NPC_FB[Math.floor(Math.random()*NPC_FB.length)]}
export async function generateAreaNarration(areaName,biome,timeOfDay,weather){const fb={forest:'Ancient trees stand like silent sentinels.',mountain:'The wind howls across jagged peaks.',coast:'Waves crash against the shore.',field:'Rolling fields stretch to the horizon.'};const key=groqKey();if(!key)return fb[biome]??`You arrive at ${areaName}.`;const text=await groqChat('You narrate a Ghost of Tsushima style game. 1-2 sentences. Atmospheric.',`Player enters ${areaName} (${biome}, ${timeOfDay}, ${weather}).`,100);return text||fb[biome]||`You arrive at ${areaName}.`}
export async function generateDynamicQuest(playerLevel,biome,completedTitles=[]){const avoid=completedTitles.length?`Avoid: ${completedTitles.join(', ')}.`:'';const raw=await groqChat('Generate quests for a samurai game. Respond ONLY with valid JSON. Types: "kill"(count 3-8),"collect"(count 3-6),"boss". Example: {"id":"q1","title":"Hunt","desc":"Desc","type":"kill","count":5,"reward":180}',`Player level ${playerLevel} in ${biome}. Generate 1 quest JSON. ${avoid}`,180);try{const match=raw.match(/\{[\s\S]*\}/);if(!match)return null;const q=JSON.parse(match[0]);if(!q.id||!q.title||!q.type)return null;q.id=`ai_${Date.now()}`;q.reward=q.reward??playerLevel*40+80;q.count=q.count??(q.type==='kill'?5:q.type==='collect'?4:undefined);return q}catch{return null}}
export async function getWeather(lat=34.5,lon=135.5){try{const res=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=weather_code&timezone=Asia%2FTokyo`);const d=await res.json();const c=d.current?.weather_code??0;if(c===0)return 'clear';if(c<=3)return 'cloudy';if(c>=51&&c<=67)return 'rain';if(c>=71&&c<=77)return 'snow';if(c>=95)return 'storm';return 'clear'}catch{return 'clear'}}
export function getSceneImageUrl(prompt,seed=null,w=1024,h=576){const s=seed??Math.floor(Math.random()*99999);return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt+', ultra detailed, cinematic')}?width=${w}&height=${h}&nologo=true&seed=${s}&model=flux`}
export async function loadSceneImage(prompt,seed){return new Promise(resolve=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=getSceneImageUrl(prompt,seed);setTimeout(()=>resolve(null),30000)})}
export async function generateQuestDialogue(questTitle,npcName,isComplete){return groqChat('You are an NPC in a samurai game. Short dialogue. 2 sentences.',isComplete?`${npcName} thanks warrior for: ${questTitle}`:`${npcName} gives quest: ${questTitle}`,100)}
