let ctx=null, master=null, enabled=true, windNode=null, lastStep=0
function ac(){if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=0.4;master.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();return ctx}
function noise(dur=0.1){const c=ac(),buf=c.createBuffer(1,c.sampleRate*dur,c.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return buf}
function env(g,a,s,r,peak=1){const now=ac().currentTime;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(peak,now+a);g.gain.setValueAtTime(peak,now+a+s);g.gain.linearRampToValueAtTime(0,now+a+s+r)}
function noiseNode(dur,freq,Q=1,type='bandpass',peak=0.3,a=0.005,s=0.02,r=0.1){const c=ac(),src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noise(dur);f.type=type;f.frequency.value=freq;f.Q.value=Q;env(g,a,s,r,peak);src.connect(f);f.connect(g);g.connect(master);src.start(c.currentTime);src.stop(c.currentTime+dur+0.02)}
export function playSwordSlash(combo=0){if(!enabled)return;noiseNode(0.15,800+combo*300,0.8,'bandpass',0.5,0.02,0.01,0.11);if(combo===3){const c=ac(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(1800,c.currentTime);o.frequency.exponentialRampToValueAtTime(400,c.currentTime+0.4);env(g,0.005,0.05,0.35,0.3);o.connect(g);g.connect(master);o.start(c.currentTime);o.stop(c.currentTime+0.45)}}
export function playHit(big=false){if(!enabled)return;const c=ac(),now=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(big?120:80,now);o.frequency.exponentialRampToValueAtTime(30,now+0.08);env(g,0.002,0.01,0.07,big?0.7:0.4);o.connect(g);g.connect(master);o.start(now);o.stop(now+0.1);noiseNode(0.05,2000,1,'highpass',0.4,0.001,0.005,0.04)}
export function playPlayerHurt(){if(!enabled)return;const c=ac(),now=c.currentTime,o=c.createOscillator(),d=c.createWaveShaper(),g=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(200,now);o.frequency.linearRampToValueAtTime(80,now+0.2);const curve=new Float32Array(256);for(let i=0;i<256;i++){const x=(i*2)/256-1;curve[i]=x<0?-0.6:0.6}d.curve=curve;env(g,0.01,0.05,0.15,0.35);o.connect(d);d.connect(g);g.connect(master);o.start(now);o.stop(now+0.25)}
export function playDodge(){if(!enabled)return;noiseNode(0.12,300,2,'bandpass',0.2,0.005,0.02,0.1)}
export function playFootstep(surface='grass'){if(!enabled)return;const now=Date.now();if(now-lastStep<280)return;lastStep=now;noiseNode(0.06,surface==='grass'?400:surface==='snow'?200:600,1,surface==='path'?'lowshelf':'bandpass',0.07,0.002,0.01,0.04)}
export function playPickup(type='coin'){if(!enabled)return;const c=ac();(type==='coin'?[880,1320,1760]:[440,550,660]).forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*0.06;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(0.2,t+0.005);g.gain.linearRampToValueAtTime(0,t+0.14);o.connect(g);g.connect(master);o.start(t);o.stop(t+0.16)})}
export function playEnemyDeath(){if(!enabled)return;const c=ac(),now=c.currentTime,o=c.createOscillator(),f=c.createBiquadFilter(),g=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(300,now);o.frequency.exponentialRampToValueAtTime(40,now+0.5);f.type='lowpass';f.frequency.setValueAtTime(2000,now);f.frequency.linearRampToValueAtTime(200,now+0.5);env(g,0.01,0.1,0.4,0.45);o.connect(f);f.connect(g);g.connect(master);o.start(now);o.stop(now+0.55)}
export function playLevelUp(){if(!enabled)return;const c=ac();[523,659,784,1047].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*0.12;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(0.3,t+0.02);g.gain.linearRampToValueAtTime(0,t+0.3);o.connect(g);g.connect(master);o.start(t);o.stop(t+0.32)})}
export function playDiscovery(){if(!enabled)return;const c=ac();[440,554,659,880].forEach((f,i)=>{[1,2].forEach(m=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*0.08;o.type='sine';o.frequency.value=f*m;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(0.18,t+0.01);g.gain.linearRampToValueAtTime(0,t+0.5);o.connect(g);g.connect(master);o.start(t);o.stop(t+0.55)})})}
export function playShrinebell(){if(!enabled)return;const c=ac(),now=c.currentTime;[523.25,659.25,783.99].forEach(f=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0.25,now);g.gain.exponentialRampToValueAtTime(0.001,now+3.5);o.connect(g);g.connect(master);o.start(now);o.stop(now+3.6)})}
export function startWind(intensity=0.5){if(!enabled||windNode)return;const c=ac(),src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=noise(3);src.loop=true;f.type='bandpass';f.frequency.value=200+intensity*300;f.Q.value=0.3;g.gain.value=0.04+intensity*0.06;src.connect(f);f.connect(g);g.connect(master);src.start();windNode={src,g}}
export function stopWind(){if(windNode){try{windNode.src.stop()}catch{}windNode=null}}
export function toggleAudio(){enabled=!enabled;if(!enabled)stopWind();else startWind(0.3);return enabled}
export function isAudioEnabled(){return enabled}
